name: MagicItemTransporter
main: tororo1066.magicitemtransporter.MagicItemTransporter
version: '1.0'
api-version: '1.21'

dependencies:
  server:
    Magic:
      required: true
    NMSUtils:
      required: true